"""add cascade delete for comments

Revision ID: 31b942620d17
Revises: 3227386d210e
Create Date: 2026-08-03 12:17:19.592135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b942620d17'
down_revision: Union[str, Sequence[str], None] = '3227386d210e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('meeting_participants_user_id_fkey'), 'meeting_participants', type_='foreignkey')
    op.create_foreign_key(None, 'meeting_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meeting_participants', type_='foreignkey')
    op.create_foreign_key(op.f('meeting_participants_user_id_fkey'), 'meeting_participants', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
