"""add cascade delete for comments

Revision ID: 3227386d210e
Revises: e5dd521caa84
Create Date: 2026-08-03 12:03:06.614206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3227386d210e'
down_revision: Union[str, Sequence[str], None] = 'e5dd521caa84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('evaluations_task_id_fkey'), 'evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'evaluations', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.create_foreign_key(op.f('evaluations_task_id_fkey'), 'evaluations', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
