"""12 migrate

Revision ID: 3fd2314cd6f5
Revises: 790ed66dade7
Create Date: 2026-07-31 16:15:51.776730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd2314cd6f5'
down_revision: Union[str, Sequence[str], None] = '790ed66dade7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('meeting_participants_meeting_id_fkey'), 'meeting_participants', type_='foreignkey')
    op.create_foreign_key(None, 'meeting_participants', 'meetings', ['meeting_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meeting_participants', type_='foreignkey')
    op.create_foreign_key(op.f('meeting_participants_meeting_id_fkey'), 'meeting_participants', 'meetings', ['meeting_id'], ['id'])
    # ### end Alembic commands ###
