"""6 migrate

Revision ID: 8d596ac4cf05
Revises: 62452512b4e5
Create Date: 2026-07-28 19:40:18.469227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d596ac4cf05'
down_revision: Union[str, Sequence[str], None] = '62452512b4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('team_members', sa.Column('last_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'last_name')
    op.drop_column('team_members', 'first_name')
    # ### end Alembic commands ###
