"""add cascade delete for comments

Revision ID: e5dd521caa84
Revises: 3fd2314cd6f5
Create Date: 2026-08-03 12:00:38.120295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5dd521caa84'
down_revision: Union[str, Sequence[str], None] = '3fd2314cd6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_task_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_task_id_fkey'), 'comments', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
